#!/bin/bash
#
# https://github.com/Nyr/wireguard-install
#
# Copyright (c) 2020 Nyr. Released under the MIT License.


# Detect Debian users running the script with "sh" instead of bash
if readlink /proc/$$/exe | grep -q "dash"; then
	echo 'This installer needs to be run with "bash", not "sh".'
	exit
fi

# Discard stdin. Needed when running from a one-liner which includes a newline
read -N 999999 -t 0.001

# Detect OS
# $os_version variables aren't always in use, but are kept here for convenience
if grep -qs "ubuntu" /etc/os-release; then
	os="ubuntu"
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
elif [[ -e /etc/debian_version ]]; then
	os="debian"
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
elif [[ -e /etc/almalinux-release || -e /etc/rocky-release || -e /etc/centos-release ]]; then
	os="centos"
	os_version=$(grep -shoE '[0-9]+' /etc/almalinux-release /etc/rocky-release /etc/centos-release | head -1)
elif [[ -e /etc/fedora-release ]]; then
	os="fedora"
	os_version=$(grep -oE '[0-9]+' /etc/fedora-release | head -1)
else
	echo "This installer seems to be running on an unsupported distribution.
Supported distros are Ubuntu, Debian, AlmaLinux, Rocky Linux, CentOS and Fedora."
	exit
fi

if [[ "$os" == "ubuntu" && "$os_version" -lt 2204 ]]; then
	echo "Ubuntu 22.04 or higher is required to use this installer.
This version of Ubuntu is too old and unsupported."
	exit
fi

if [[ "$os" == "debian" ]]; then
	if grep -q '/sid' /etc/debian_version; then
		echo "Debian Testing and Debian Unstable are unsupported by this installer."
		exit
	fi
	if [[ "$os_version" -lt 11 ]]; then
		echo "Debian 11 or higher is required to use this installer.
This version of Debian is too old and unsupported."
		exit
	fi
fi

if [[ "$os" == "centos" && "$os_version" -lt 9 ]]; then
	os_name=$(sed 's/ release.*//' /etc/almalinux-release /etc/rocky-release /etc/centos-release 2>/dev/null | head -1)
	echo "$os_name 9 or higher is required to use this installer.
This version of $os_name is too old and unsupported."
	exit
fi

# Detect environments where $PATH does not include the sbin directories
if ! grep -q sbin <<< "$PATH"; then
	echo '$PATH does not include sbin. Try using "su -" instead of "su".'
	exit
fi

# Detect if BoringTun (userspace WireGuard) needs to be used
if ! systemd-detect-virt -cq; then
	# Not running inside a container
	use_boringtun="0"
elif grep -q '^wireguard ' /proc/modules; then
	# Running inside a container, but the wireguard kernel module is available
	use_boringtun="0"
else
	# Running inside a container and the wireguard kernel module is not available
	use_boringtun="1"
fi

if [[ "$EUID" -ne 0 ]]; then
	echo "This installer needs to be run with superuser privileges."
	exit
fi

if [[ "$use_boringtun" -eq 1 ]]; then
	if [ "$(uname -m)" != "x86_64" ]; then
		echo "In containerized systems without the wireguard kernel module, this installer
supports only the x86_64 architecture.
The system runs on $(uname -m) and is unsupported."
		exit
	fi
	# TUN device is required to use BoringTun
	if [[ ! -e /dev/net/tun ]] || ! ( exec 7<>/dev/net/tun ) 2>/dev/null; then
		echo "The system does not have the TUN device available.
TUN needs to be enabled before running this installer."
		exit
	fi
fi

# Store the absolute path of the directory where the script is located
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

valid_ipv4_octet () {
	[[ "$1" =~ ^[0-9]+$ ]] && (( 10#$1 >= 0 && 10#$1 <= 255 ))
}

valid_ipv4_subnet () {
	local first second third extra
	IFS=. read -r first second third extra <<< "$1"
	[[ -z "$extra" ]] || return 1
	valid_ipv4_octet "$first" && valid_ipv4_octet "$second" && valid_ipv4_octet "$third"
}

wg_ipv4_address () {
	grep '^Address' /etc/wireguard/wg0.conf | cut -d " " -f 3 | tr ',' '\n' | grep -m 1 -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]+'
}

wg_ipv4_subnet () {
	wg_ipv4_address | cut -d "/" -f 1 | cut -d "." -f 1-3
}

wg_ipv4_cidr () {
	echo "$(wg_ipv4_subnet).0/24"
}

next_ipv4_subnet () {
	local first second third extra
	IFS=. read -r first second third extra <<< "$1"
	if (( 10#$third < 255 )); then
		echo "$first.$second.$((10#$third+1))"
	else
		echo "$first.$second.254"
	fi
}

wg_ipv6_cidr () {
	grep '^Address' /etc/wireguard/wg0.conf | cut -d " " -f 3- | tr ',' '\n' | grep -m 1 -oE '([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}/[0-9]+' | sed 's/::1\/64$/::\/64/'
}

write_extra_in_config () {
	local extra_port="$1"
	local extra_subnet="$2"
	local tmp_extra_in wg0_private_key
	wg0_private_key=$(grep '^PrivateKey' /etc/wireguard/wg0.conf | cut -d " " -f 3)
	tmp_extra_in=$(mktemp)
	cat << EOF > "$tmp_extra_in"
# Generated by wireguard-install 2nd hop upstream tun
[Interface]
Address = $extra_subnet.1/24
PrivateKey = $wg0_private_key
ListenPort = $extra_port
Table = off

EOF
	sed -n '/^# BEGIN_PEER /,/^# END_PEER /p' /etc/wireguard/wg0.conf | awk -v extra_subnet="$extra_subnet" '
		/^AllowedIPs = / {
			split($3, ip_parts, ".")
			split(ip_parts[4], last_octet, "/")
			print "AllowedIPs = " extra_subnet "." last_octet[1] "/32"
			next
		}
		{ print }
	' >> "$tmp_extra_in"
	cat "$tmp_extra_in" > /etc/wireguard/wg-extra-in.conf
	rm -f "$tmp_extra_in"
	chmod 600 /etc/wireguard/wg-extra-in.conf
}

sync_extra_in_peers () {
	if [[ ! -e /etc/wireguard/wg-extra-in.conf || ! -e /etc/wireguard/wg-extra-tun.env ]]; then
		return
	fi
	extra_port=$(grep '^EXTRA_PORT=' /etc/wireguard/wg-extra-tun.env | cut -d "=" -f 2)
	extra_subnet=$(grep '^EXTRA_VPN_SUBNET=' /etc/wireguard/wg-extra-tun.env | cut -d "=" -f 2)
	if [[ -z "$extra_port" || -z "$extra_subnet" ]]; then
		return
	fi
	write_extra_in_config "$extra_port" "$extra_subnet"
	if systemctl is-active --quiet wg-quick@wg-extra-in.service; then
		wg syncconf wg-extra-in <(wg-quick strip wg-extra-in)
	fi
}

write_extra_rules_script () {
	cat << 'EOF' > /usr/local/sbin/wg-extra-tun-rules
#!/bin/bash
set -e

. /etc/wireguard/wg-extra-tun.env

add_iptables_rule () {
	local table="$1"
	shift
	"$IPTABLES_PATH" -w 5 -t "$table" -C "$@" 2>/dev/null || "$IPTABLES_PATH" -w 5 -t "$table" -A "$@"
}

insert_iptables_rule () {
	local table="$1"
	local chain="$2"
	shift 2
	"$IPTABLES_PATH" -w 5 -t "$table" -C "$chain" "$@" 2>/dev/null || "$IPTABLES_PATH" -w 5 -t "$table" -I "$chain" 1 "$@"
}

del_iptables_rule () {
	local table="$1"
	shift
	while "$IPTABLES_PATH" -w 5 -t "$table" -C "$@" 2>/dev/null; do
		"$IPTABLES_PATH" -w 5 -t "$table" -D "$@"
	done
}

add_ip6tables_rule () {
	local table="$1"
	shift
	"$IP6TABLES_PATH" -w 5 -t "$table" -C "$@" 2>/dev/null || "$IP6TABLES_PATH" -w 5 -t "$table" -A "$@"
}

insert_ip6tables_rule () {
	local table="$1"
	local chain="$2"
	shift 2
	"$IP6TABLES_PATH" -w 5 -t "$table" -C "$chain" "$@" 2>/dev/null || "$IP6TABLES_PATH" -w 5 -t "$table" -I "$chain" 1 "$@"
}

del_ip6tables_rule () {
	local table="$1"
	shift
	while "$IP6TABLES_PATH" -w 5 -t "$table" -C "$@" 2>/dev/null; do
		"$IP6TABLES_PATH" -w 5 -t "$table" -D "$@"
	done
}

firewalld_direct () {
	firewall-cmd --direct "$@" 2>/dev/null || true
}

set_kernel_settings () {
	echo 1 > /proc/sys/net/ipv4/ip_forward
	echo 1 > /proc/sys/net/ipv4/conf/all/src_valid_mark 2>/dev/null || true
	for iface in all default "$EXTRA_IN_IF" "$EXTRA_UP_IF"; do
		if [[ -e "/proc/sys/net/ipv4/conf/$iface/rp_filter" ]]; then
			echo 0 > "/proc/sys/net/ipv4/conf/$iface/rp_filter"
		fi
	done
	if [[ -n "$VPN6_CIDR" ]]; then
		echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
	fi
}

start_routes () {
	ip rule show | grep -q "iif $EXTRA_IN_IF lookup $EXTRA_TABLE" || ip rule add iif "$EXTRA_IN_IF" table "$EXTRA_TABLE" priority "$EXTRA_IIF_PRIORITY"
	ip rule show | grep -q "fwmark $EXTRA_MARK lookup $EXTRA_TABLE" || ip rule add fwmark "$EXTRA_MARK" table "$EXTRA_TABLE" priority "$EXTRA_MARK_PRIORITY"
	ip route replace "$VPN_CIDR" dev "$EXTRA_IN_IF" table "$EXTRA_TABLE"
	ip route replace default dev "$EXTRA_UP_IF" table "$EXTRA_TABLE"
	if [[ -n "$VPN6_CIDR" ]]; then
		ip -6 rule show | grep -q "iif $EXTRA_IN_IF lookup $EXTRA_TABLE" || ip -6 rule add iif "$EXTRA_IN_IF" table "$EXTRA_TABLE" priority "$EXTRA_IIF_PRIORITY"
		ip -6 rule show | grep -q "fwmark $EXTRA_MARK lookup $EXTRA_TABLE" || ip -6 rule add fwmark "$EXTRA_MARK" table "$EXTRA_TABLE" priority "$EXTRA_MARK_PRIORITY"
		ip -6 route replace "$VPN6_CIDR" dev "$EXTRA_IN_IF" table "$EXTRA_TABLE"
		ip -6 route replace default dev "$EXTRA_UP_IF" table "$EXTRA_TABLE"
	fi
	ip route flush cache
}

stop_routes () {
	ip route del default dev "$EXTRA_UP_IF" table "$EXTRA_TABLE" 2>/dev/null || true
	ip route del "$VPN_CIDR" dev "$EXTRA_IN_IF" table "$EXTRA_TABLE" 2>/dev/null || true
	while ip rule show | grep -q "iif $EXTRA_IN_IF lookup $EXTRA_TABLE"; do
		ip rule del iif "$EXTRA_IN_IF" table "$EXTRA_TABLE" priority "$EXTRA_IIF_PRIORITY" 2>/dev/null || break
	done
	while ip rule show | grep -q "fwmark $EXTRA_MARK lookup $EXTRA_TABLE"; do
		ip rule del fwmark "$EXTRA_MARK" table "$EXTRA_TABLE" priority "$EXTRA_MARK_PRIORITY" 2>/dev/null || break
	done
	if [[ -n "$VPN6_CIDR" ]]; then
		ip -6 route del default dev "$EXTRA_UP_IF" table "$EXTRA_TABLE" 2>/dev/null || true
		ip -6 route del "$VPN6_CIDR" dev "$EXTRA_IN_IF" table "$EXTRA_TABLE" 2>/dev/null || true
		while ip -6 rule show | grep -q "iif $EXTRA_IN_IF lookup $EXTRA_TABLE"; do
			ip -6 rule del iif "$EXTRA_IN_IF" table "$EXTRA_TABLE" priority "$EXTRA_IIF_PRIORITY" 2>/dev/null || break
		done
		while ip -6 rule show | grep -q "fwmark $EXTRA_MARK lookup $EXTRA_TABLE"; do
			ip -6 rule del fwmark "$EXTRA_MARK" table "$EXTRA_TABLE" priority "$EXTRA_MARK_PRIORITY" 2>/dev/null || break
		done
	fi
	ip route flush cache
}

start_firewall () {
	if systemctl is-active --quiet firewalld.service; then
		firewall-cmd --add-port="$EXTRA_PORT"/udp
		firewalld_direct --add-rule ipv4 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
		firewalld_direct --add-rule ipv4 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
		firewalld_direct --add-rule ipv4 mangle PREROUTING 0 -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
		firewalld_direct --add-rule ipv4 mangle FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		firewalld_direct --add-rule ipv4 mangle FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		firewalld_direct --add-rule ipv4 nat POSTROUTING -10 -s "$VPN_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
		firewalld_direct --add-rule ipv4 filter FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN_CIDR" -j ACCEPT
		firewalld_direct --add-rule ipv4 filter FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		if [[ -n "$VPN6_CIDR" ]]; then
			firewalld_direct --add-rule ipv6 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
			firewalld_direct --add-rule ipv6 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
			firewalld_direct --add-rule ipv6 mangle PREROUTING 0 -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
			firewalld_direct --add-rule ipv6 mangle FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			firewalld_direct --add-rule ipv6 mangle FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			firewalld_direct --add-rule ipv6 nat POSTROUTING -10 -s "$VPN6_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
			firewalld_direct --add-rule ipv6 filter FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN6_CIDR" -j ACCEPT
			firewalld_direct --add-rule ipv6 filter FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN6_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		fi
	else
		add_iptables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
		add_iptables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
		add_iptables_rule mangle PREROUTING -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
		add_iptables_rule mangle FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		add_iptables_rule mangle FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		insert_iptables_rule nat POSTROUTING -s "$VPN_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
		add_iptables_rule filter INPUT -p udp --dport "$EXTRA_PORT" -j ACCEPT
		add_iptables_rule filter FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN_CIDR" -j ACCEPT
		add_iptables_rule filter FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		if [[ -n "$VPN6_CIDR" ]]; then
			add_ip6tables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
			add_ip6tables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
			add_ip6tables_rule mangle PREROUTING -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
			add_ip6tables_rule mangle FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			add_ip6tables_rule mangle FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			insert_ip6tables_rule nat POSTROUTING -s "$VPN6_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
			add_ip6tables_rule filter FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN6_CIDR" -j ACCEPT
			add_ip6tables_rule filter FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN6_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		fi
	fi
}

stop_firewall () {
	if systemctl is-active --quiet firewalld.service; then
		firewall-cmd --remove-port="$EXTRA_PORT"/udp 2>/dev/null || true
		firewalld_direct --remove-rule ipv4 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
		firewalld_direct --remove-rule ipv4 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
		firewalld_direct --remove-rule ipv4 mangle PREROUTING 0 -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
		firewalld_direct --remove-rule ipv4 mangle FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		firewalld_direct --remove-rule ipv4 mangle FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		firewalld_direct --remove-rule ipv4 nat POSTROUTING -10 -s "$VPN_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
		firewalld_direct --remove-rule ipv4 nat POSTROUTING 0 -s "$VPN_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
		firewalld_direct --remove-rule ipv4 filter FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN_CIDR" -j ACCEPT
		firewalld_direct --remove-rule ipv4 filter FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		if [[ -n "$VPN6_CIDR" ]]; then
			firewalld_direct --remove-rule ipv6 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
			firewalld_direct --remove-rule ipv6 mangle PREROUTING 0 -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
			firewalld_direct --remove-rule ipv6 mangle PREROUTING 0 -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
			firewalld_direct --remove-rule ipv6 mangle FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			firewalld_direct --remove-rule ipv6 mangle FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			firewalld_direct --remove-rule ipv6 nat POSTROUTING -10 -s "$VPN6_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
			firewalld_direct --remove-rule ipv6 nat POSTROUTING 0 -s "$VPN6_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
			firewalld_direct --remove-rule ipv6 filter FORWARD 0 -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN6_CIDR" -j ACCEPT
			firewalld_direct --remove-rule ipv6 filter FORWARD 0 -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN6_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		fi
	else
		del_iptables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
		del_iptables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
		del_iptables_rule mangle PREROUTING -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
		del_iptables_rule mangle FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		del_iptables_rule mangle FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		del_iptables_rule nat POSTROUTING -s "$VPN_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
		del_iptables_rule filter INPUT -p udp --dport "$EXTRA_PORT" -j ACCEPT
		del_iptables_rule filter FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN_CIDR" -j ACCEPT
		del_iptables_rule filter FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		if [[ -n "$VPN6_CIDR" ]]; then
			del_ip6tables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j MARK --set-mark "$EXTRA_MARK"
			del_ip6tables_rule mangle PREROUTING -i "$EXTRA_IN_IF" -j CONNMARK --save-mark
			del_ip6tables_rule mangle PREROUTING -i "$EXTRA_UP_IF" -j CONNMARK --restore-mark
			del_ip6tables_rule mangle FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			del_ip6tables_rule mangle FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
			del_ip6tables_rule nat POSTROUTING -s "$VPN6_CIDR" -o "$EXTRA_UP_IF" -j MASQUERADE
			del_ip6tables_rule filter FORWARD -i "$EXTRA_IN_IF" -o "$EXTRA_UP_IF" -s "$VPN6_CIDR" -j ACCEPT
			del_ip6tables_rule filter FORWARD -i "$EXTRA_UP_IF" -o "$EXTRA_IN_IF" -d "$VPN6_CIDR" -m state --state RELATED,ESTABLISHED -j ACCEPT
		fi
	fi
}

case "$1" in
	start)
		set_kernel_settings
		start_routes
		start_firewall
	;;
	stop)
		stop_firewall
		stop_routes
	;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
	;;
esac
EOF
	chmod +x /usr/local/sbin/wg-extra-tun-rules
}

add_extra_tun () {
	if [[ -e /etc/wireguard/wg-extra-tun.env ]]; then
		echo
		echo "2nd hop upstream tun is already installed."
		exit
	fi
	shopt -s nullglob
	config_files=("$script_dir"/*.conf)
	shopt -u nullglob
	if [[ "${#config_files[@]}" -eq 0 ]]; then
		echo
		echo "No .conf files were found in $script_dir."
		exit
	fi
	echo
	echo "Select the WireGuard config for the upstream server:"
	for i in "${!config_files[@]}"; do
		echo "   $((i+1))) $(basename "${config_files[$i]}")"
	done
	read -p "Config: " config_number
	until [[ "$config_number" =~ ^[0-9]+$ && "$config_number" -ge 1 && "$config_number" -le "${#config_files[@]}" ]]; do
		echo "$config_number: invalid selection."
		read -p "Config: " config_number
	done
	upstream_config="${config_files[$((config_number-1))]}"
	if ! grep -q '^\[Interface\]' "$upstream_config" || ! grep -q '^\[Peer\]' "$upstream_config" || ! grep -q '^Endpoint' "$upstream_config"; then
		echo
		echo "$(basename "$upstream_config") does not look like a complete WireGuard client config."
		exit
	fi
	main_port=$(grep '^ListenPort' /etc/wireguard/wg0.conf | cut -d " " -f 3)
	echo
	echo "What port should the extra WireGuard entry listen on?"
	read -p "Port [51821]: " extra_port
	until [[ -z "$extra_port" || "$extra_port" =~ ^[0-9]+$ && "$extra_port" -le 65535 && "$extra_port" != "$main_port" ]]; do
		echo "$extra_port: invalid port."
		read -p "Port [51821]: " extra_port
	done
	[[ -z "$extra_port" ]] && extra_port="51821"
	if [[ "$extra_port" == "$main_port" ]]; then
		echo
		echo "2nd hop upstream tun port cannot be the same as the main WireGuard port."
		exit
	fi
	main_subnet=$(wg_ipv4_subnet)
	default_extra_subnet=$(next_ipv4_subnet "$main_subnet")
	echo
	echo "What IPv4 subnet should 2nd hop upstream tun use?"
	read -p "2nd hop subnet [$default_extra_subnet]: " extra_subnet
	until [[ -z "$extra_subnet" ]] || { valid_ipv4_subnet "$extra_subnet" && [[ "$extra_subnet" != "$main_subnet" ]]; }; do
		echo "$extra_subnet: invalid subnet. Use the first three IPv4 octets and do not reuse $main_subnet."
		read -p "2nd hop subnet [$default_extra_subnet]: " extra_subnet
	done
	[[ -z "$extra_subnet" ]] && extra_subnet="$default_extra_subnet"
	awk '
		/^[[:space:]]*\[Interface\][[:space:]]*$/ {
			in_interface=1
			table_seen=0
			print
			next
		}
		/^[[:space:]]*\[/ {
			if (in_interface && !table_seen) {
				print "Table = off"
			}
			in_interface=0
		}
		in_interface && /^[[:space:]]*DNS[[:space:]]*=/ {
			next
		}
		in_interface && /^[[:space:]]*Table[[:space:]]*=/ {
			if (!table_seen) {
				print "Table = off"
			}
			table_seen=1
			next
		}
		{ print }
		END {
			if (in_interface && !table_seen) {
				print "Table = off"
			}
		}
	' "$upstream_config" > /etc/wireguard/wg-extra-up.conf
	chmod 600 /etc/wireguard/wg-extra-up.conf
	write_extra_in_config "$extra_port" "$extra_subnet"
	iptables_path=$(command -v iptables)
	ip6tables_path=$(command -v ip6tables)
	if [[ $(systemd-detect-virt) == "openvz" ]] && readlink -f "$(command -v iptables)" | grep -q "nft" && hash iptables-legacy 2>/dev/null; then
		iptables_path=$(command -v iptables-legacy)
		ip6tables_path=$(command -v ip6tables-legacy)
	fi
	cat << EOF > /etc/wireguard/wg-extra-tun.env
EXTRA_PORT=$extra_port
EXTRA_TABLE=$extra_port
EXTRA_MARK=0xca6d
EXTRA_IIF_PRIORITY=10021
EXTRA_MARK_PRIORITY=10022
EXTRA_IN_IF=wg-extra-in
EXTRA_UP_IF=wg-extra-up
EXTRA_VPN_SUBNET=$extra_subnet
VPN_CIDR=$extra_subnet.0/24
VPN6_CIDR=
IPTABLES_PATH=$iptables_path
IP6TABLES_PATH=$ip6tables_path
EOF
	chmod 600 /etc/wireguard/wg-extra-tun.env
	generated_extra_configs=0
	old_client="$client"
	while read -r existing_client; do
		if [[ -e "$script_dir"/"$existing_client.conf" ]]; then
			client="$existing_client"
			new_client_extra_setup
			(( generated_extra_configs++ ))
		fi
	done < <(grep '^# BEGIN_PEER' /etc/wireguard/wg0.conf | cut -d ' ' -f 3)
	client="$old_client"
	write_extra_rules_script
	cat << EOF > /etc/systemd/system/wg-extra-tun.service
[Unit]
After=network-online.target wg-quick@wg-extra-up.service wg-quick@wg-extra-in.service
Wants=network-online.target wg-quick@wg-extra-up.service wg-quick@wg-extra-in.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/wg-extra-tun-rules start
ExecStop=/usr/local/sbin/wg-extra-tun-rules stop
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
	if [[ "$use_boringtun" -eq 1 ]]; then
		mkdir -p /etc/systemd/system/wg-quick@wg-extra-up.service.d/ /etc/systemd/system/wg-quick@wg-extra-in.service.d/
		echo "[Service]
Environment=WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun
Environment=WG_SUDO=1" > /etc/systemd/system/wg-quick@wg-extra-up.service.d/boringtun.conf
		echo "[Service]
Environment=WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun
Environment=WG_SUDO=1" > /etc/systemd/system/wg-quick@wg-extra-in.service.d/boringtun.conf
	fi
	systemctl daemon-reload
	systemctl enable --now wg-quick@wg-extra-up.service
	systemctl enable --now wg-quick@wg-extra-in.service
	systemctl enable --now wg-extra-tun.service
	echo
	echo "2nd hop upstream tun added. Clients using port $extra_port will be routed through $(basename "$upstream_config")."
	echo "2nd hop upstream tun clients will use the $extra_subnet.0/24 subnet."
	if [[ "$generated_extra_configs" -gt 0 ]]; then
		echo "Generated $generated_extra_configs 2nd hop upstream tun client config(s) in $script_dir."
	fi
}

remove_extra_tun () {
	if [[ ! -e /etc/wireguard/wg-extra-tun.env ]]; then
		echo
		echo "2nd hop upstream tun is not installed."
		exit
	fi
	systemctl disable --now wg-extra-tun.service 2>/dev/null || true
	systemctl disable --now wg-quick@wg-extra-in.service 2>/dev/null || true
	systemctl disable --now wg-quick@wg-extra-up.service 2>/dev/null || true
	rm -f /etc/systemd/system/wg-extra-tun.service
	rm -f /usr/local/sbin/wg-extra-tun-rules
	rm -f /etc/wireguard/wg-extra-tun.env
	rm -f /etc/wireguard/wg-extra-in.conf
	rm -f /etc/wireguard/wg-extra-up.conf
	rm -rf /etc/systemd/system/wg-quick@wg-extra-up.service.d/
	rm -rf /etc/systemd/system/wg-quick@wg-extra-in.service.d/
	systemctl daemon-reload
	echo
	echo "2nd hop upstream tun removed."
}

new_client_dns () {
	echo "Select a DNS server for the client:"
	echo "   1) Default system resolvers"
	echo "   2) Google"
	echo "   3) 1.1.1.1"
	echo "   4) OpenDNS"
	echo "   5) Quad9"
	echo "   6) Gcore"
	echo "   7) AdGuard"
	echo "   8) Specify custom resolvers"
	read -p "DNS server [1]: " dns
	until [[ -z "$dns" || "$dns" =~ ^[1-8]$ ]]; do
		echo "$dns: invalid selection."
		read -p "DNS server [1]: " dns
	done
	case "$dns" in
		1|"")
			# Locate the proper resolv.conf
			# Needed for systems running systemd-resolved
			if grep '^nameserver' "/etc/resolv.conf" | grep -qv '127.0.0.53' ; then
				resolv_conf="/etc/resolv.conf"
			else
				resolv_conf="/run/systemd/resolve/resolv.conf"
			fi
			# Extract nameservers and provide them in the required format
			dns=$(grep -v '^#\|^;' "$resolv_conf" | grep '^nameserver' | grep -v '127.0.0.53' | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | xargs | sed -e 's/ /, /g')
		;;
		2)
			dns="8.8.8.8, 8.8.4.4"
		;;
		3)
			dns="1.1.1.1, 1.0.0.1"
		;;
		4)
			dns="208.67.222.222, 208.67.220.220"
		;;
		5)
			dns="9.9.9.9, 149.112.112.112"
		;;
		6)
			dns="95.85.95.85, 2.56.220.2"
		;;
		7)
			dns="94.140.14.14, 94.140.15.15"
		;;
		8)
			echo
			until [[ -n "$custom_dns" ]]; do
				echo "Enter DNS servers (one or more IPv4 addresses, separated by commas or spaces):"
				read -p "DNS servers: " dns_input
				# Convert comma delimited to space delimited
				dns_input=$(echo "$dns_input" | tr ',' ' ')
				# Validate and build custom DNS IP list
				for dns_ip in $dns_input; do
					if [[ "$dns_ip" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
						if [[ -z "$custom_dns" ]]; then
							custom_dns="$dns_ip"
						else
							custom_dns="$custom_dns, $dns_ip"
						fi
					fi
				done
				if [ -z "$custom_dns" ]; then
					echo "Invalid input."
				else
					dns="$custom_dns"
				fi
			done
		;;
	esac
}

new_client_setup () {
	vpn_subnet=$(wg_ipv4_subnet)
	# Given a list of the assigned internal IPv4 addresses, obtain the lowest still
	# available octet. Important to start looking at 2, because 1 is our gateway.
	octet=2
	while grep AllowedIPs /etc/wireguard/wg0.conf | cut -d "." -f 4 | cut -d "/" -f 1 | grep -q "^$octet$"; do
		(( octet++ ))
	done
	# Don't break the WireGuard configuration in case the address space is full
	if [[ "$octet" -eq 255 ]]; then
		echo "253 clients are already configured. The WireGuard internal subnet is full!"
		exit
	fi
	key=$(wg genkey)
	psk=$(wg genpsk)
	# Configure client in the server
	cat << EOF >> /etc/wireguard/wg0.conf
# BEGIN_PEER $client
[Peer]
PublicKey = $(wg pubkey <<< $key)
PresharedKey = $psk
AllowedIPs = $vpn_subnet.$octet/32$(grep -q 'fddd:2c4:2c4:2c4::1' /etc/wireguard/wg0.conf && echo ", fddd:2c4:2c4:2c4::$octet/128")
# END_PEER $client
EOF
	# Create client configuration
	cat << EOF > "$script_dir"/"$client".conf
[Interface]
Address = $vpn_subnet.$octet/24$(grep -q 'fddd:2c4:2c4:2c4::1' /etc/wireguard/wg0.conf && echo ", fddd:2c4:2c4:2c4::$octet/64")
DNS = $dns
PrivateKey = $key

[Peer]
PublicKey = $(grep PrivateKey /etc/wireguard/wg0.conf | cut -d " " -f 3 | wg pubkey)
PresharedKey = $psk
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = $(grep '^# ENDPOINT' /etc/wireguard/wg0.conf | cut -d " " -f 3):$(grep ListenPort /etc/wireguard/wg0.conf | cut -d " " -f 3)
PersistentKeepalive = 25
EOF
}

new_client_extra_setup () {
	if [[ ! -e /etc/wireguard/wg-extra-tun.env ]]; then
		return
	fi
	extra_port=$(grep '^EXTRA_PORT=' /etc/wireguard/wg-extra-tun.env | cut -d "=" -f 2)
	extra_subnet=$(grep '^EXTRA_VPN_SUBNET=' /etc/wireguard/wg-extra-tun.env | cut -d "=" -f 2)
	if [[ -z "$extra_port" || -z "$extra_subnet" ]]; then
		return
	fi
	awk -v extra_port="$extra_port" -v extra_subnet="$extra_subnet" '
		/^Address = / {
			split($3, ip_parts, ".")
			split(ip_parts[4], last_octet, "/")
			print "Address = " extra_subnet "." last_octet[1] "/24"
			next
		}
		/^Endpoint = / {
			sub(/:[0-9]+$/, ":" extra_port)
			print
			next
		}
		/^AllowedIPs = / {
			print "AllowedIPs = 0.0.0.0/0"
			next
		}
		{ print }
	' "$script_dir"/"$client.conf" > "$script_dir"/"$client-2nd-hop-upstream.conf"
}

print_client_qr_codes () {
	echo
	echo "DIRECT CONFIG ($client.conf)"
	echo
	qrencode -t ANSI256UTF8 < "$script_dir"/"$client.conf"
	echo
	echo "Direct client configuration is available in:" "$script_dir"/"$client.conf"
	if [[ -e "$script_dir"/"$client-2nd-hop-upstream.conf" ]]; then
		printf '\n\n\n\n\n\n\n\n'
		echo "2ND HOP UPSTREAM TUN CONFIG ($client-2nd-hop-upstream.conf)"
		echo
		qrencode -t ANSI256UTF8 < "$script_dir"/"$client-2nd-hop-upstream.conf"
		echo
		echo "2nd hop upstream tun client configuration is available in:" "$script_dir"/"$client-2nd-hop-upstream.conf"
	fi
}

if [[ ! -e /etc/wireguard/wg0.conf ]]; then
	# Detect some Debian minimal setups where neither wget nor curl are installed
	if ! hash wget 2>/dev/null && ! hash curl 2>/dev/null; then
		echo "Wget is required to use this installer."
		read -n1 -r -p "Press any key to install Wget and continue..."
		apt-get update
		apt-get install -y wget
	fi
	clear
	echo 'Welcome to this WireGuard road warrior installer!'
	# If system has a single IPv4, it is selected automatically. Else, ask the user
	if [[ $(ip -4 addr | grep inet | grep -vEc '127(\.[0-9]{1,3}){3}') -eq 1 ]]; then
		ip=$(ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}')
	else
		number_of_ip=$(ip -4 addr | grep inet | grep -vEc '127(\.[0-9]{1,3}){3}')
		echo
		echo "Which IPv4 address should be used?"
		ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | nl -s ') '
		read -p "IPv4 address [1]: " ip_number
		until [[ -z "$ip_number" || "$ip_number" =~ ^[0-9]+$ && "$ip_number" -le "$number_of_ip" ]]; do
			echo "$ip_number: invalid selection."
			read -p "IPv4 address [1]: " ip_number
		done
		[[ -z "$ip_number" ]] && ip_number="1"
		ip=$(ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | sed -n "$ip_number"p)
	fi
	# If $ip is a private IP address, the server must be behind NAT
	if echo "$ip" | grep -qE '^(10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.|192\.168)'; then
		echo
		echo "This server is behind NAT. What is the public IPv4 address or hostname?"
		# Get public IP and sanitize with grep
		get_public_ip=$(grep -m 1 -oE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' <<< "$(wget -T 10 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/" || curl -m 10 -4Ls "http://ip1.dynupdate.no-ip.com/")")
		read -p "Public IPv4 address / hostname [$get_public_ip]: " public_ip
		# If the checkip service is unavailable and user didn't provide input, ask again
		until [[ -n "$get_public_ip" || -n "$public_ip" ]]; do
			echo "Invalid input."
			read -p "Public IPv4 address / hostname: " public_ip
		done
		[[ -z "$public_ip" ]] && public_ip="$get_public_ip"
	fi
	# If system has a single IPv6, it is selected automatically
	if [[ $(ip -6 addr | grep -c 'inet6 [23]') -eq 1 ]]; then
		ip6=$(ip -6 addr | grep 'inet6 [23]' | cut -d '/' -f 1 | grep -oE '([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}')
	fi
	# If system has multiple IPv6, ask the user to select one
	if [[ $(ip -6 addr | grep -c 'inet6 [23]') -gt 1 ]]; then
		number_of_ip6=$(ip -6 addr | grep -c 'inet6 [23]')
		echo
		echo "Which IPv6 address should be used?"
		ip -6 addr | grep 'inet6 [23]' | cut -d '/' -f 1 | grep -oE '([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}' | nl -s ') '
		read -p "IPv6 address [1]: " ip6_number
		until [[ -z "$ip6_number" || "$ip6_number" =~ ^[0-9]+$ && "$ip6_number" -le "$number_of_ip6" ]]; do
			echo "$ip6_number: invalid selection."
			read -p "IPv6 address [1]: " ip6_number
		done
		[[ -z "$ip6_number" ]] && ip6_number="1"
		ip6=$(ip -6 addr | grep 'inet6 [23]' | cut -d '/' -f 1 | grep -oE '([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}' | sed -n "$ip6_number"p)
	fi
	echo
	echo "What IPv4 subnet should WireGuard use?"
	read -p "Subnet [10.7.0]: " vpn_subnet
	until [[ -z "$vpn_subnet" ]] || valid_ipv4_subnet "$vpn_subnet"; do
		echo "$vpn_subnet: invalid subnet. Use the first three IPv4 octets, for example 10.7.0."
		read -p "Subnet [10.7.0]: " vpn_subnet
	done
	[[ -z "$vpn_subnet" ]] && vpn_subnet="10.7.0"
	echo
	echo "What port should WireGuard listen on?"
	read -p "Port [51820]: " port
	until [[ -z "$port" || "$port" =~ ^[0-9]+$ && "$port" -le 65535 ]]; do
		echo "$port: invalid port."
		read -p "Port [51820]: " port
	done
	[[ -z "$port" ]] && port="51820"
	echo
	echo "Enter a name for the first client:"
	read -p "Name [client]: " unsanitized_client
	# Allow a limited length and set of characters to avoid conflicts
	client=$(sed 's/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-]/_/g' <<< "$unsanitized_client" | cut -c-15)
	[[ -z "$client" ]] && client="client"
	echo
	new_client_dns
	# Set up automatic updates for BoringTun if the user is fine with that
	if [[ "$use_boringtun" -eq 1 ]]; then
		echo
		echo "BoringTun will be installed to set up WireGuard on the system."
		read -p "Should automatic updates be enabled for it? [Y/n]: " boringtun_updates
		until [[ "$boringtun_updates" =~ ^[yYnN]*$ ]]; do
			echo "$boringtun_updates: invalid selection."
			read -p "Should automatic updates be enabled for it? [Y/n]: " boringtun_updates
		done
		[[ -z "$boringtun_updates" ]] && boringtun_updates="y"
		if [[ "$boringtun_updates" =~ ^[yY]$ ]]; then
			if [[ "$os" == "centos" || "$os" == "fedora" ]]; then
				cron="cronie"
			elif [[ "$os" == "debian" || "$os" == "ubuntu" ]]; then
				cron="cron"
			fi
		fi
	fi
	echo
	echo "WireGuard installation is ready to begin."
	# Install a firewall if firewalld or iptables are not already available
	if ! systemctl is-active --quiet firewalld.service && ! hash iptables 2>/dev/null; then
		if [[ "$os" == "centos" || "$os" == "fedora" ]]; then
			firewall="firewalld"
			# We don't want to silently enable firewalld, so we give a subtle warning
			# If the user continues, firewalld will be installed and enabled during setup
			echo "firewalld, which is required to manage routing tables, will also be installed."
		elif [[ "$os" == "debian" || "$os" == "ubuntu" ]]; then
			# iptables is way less invasive than firewalld so no warning is given
			firewall="iptables"
		fi
	fi
	read -n1 -r -p "Press any key to continue..."
	# Install WireGuard
	# If BoringTun is not required, set up with the WireGuard kernel module
	if [[ "$use_boringtun" -eq 0 ]]; then
		if [[ "$os" == "ubuntu" ]]; then
			# Ubuntu
			apt-get update
			apt-get install -y wireguard qrencode $firewall
		elif [[ "$os" == "debian" ]]; then
			# Debian
			apt-get update
			apt-get install -y wireguard qrencode $firewall
		elif [[ "$os" == "centos" ]]; then
			# CentOS
			dnf install -y epel-release
			dnf install -y wireguard-tools qrencode $firewall
		elif [[ "$os" == "fedora" ]]; then
			# Fedora
			dnf install -y wireguard-tools qrencode $firewall
			mkdir -p /etc/wireguard/
		fi
	# Else, BoringTun needs to be used
	else
		# Install required packages
		if [[ "$os" == "ubuntu" ]]; then
			# Ubuntu
			apt-get update
			apt-get install -y qrencode ca-certificates $cron $firewall
			apt-get install -y wireguard-tools --no-install-recommends
		elif [[ "$os" == "debian" ]]; then
			# Debian
			apt-get update
			apt-get install -y qrencode ca-certificates $cron $firewall
			apt-get install -y wireguard-tools --no-install-recommends
		elif [[ "$os" == "centos" ]]; then
			# CentOS
			dnf install -y epel-release
			dnf install -y wireguard-tools qrencode ca-certificates tar $cron $firewall
		elif [[ "$os" == "fedora" ]]; then
			# Fedora
			dnf install -y wireguard-tools qrencode ca-certificates tar $cron $firewall
			mkdir -p /etc/wireguard/
		fi
		# Grab the BoringTun binary using wget or curl and extract into the right place.
		# Don't use this service elsewhere without permission! Contact me before you do!
		{ wget -qO- https://wg.nyr.be/1/latest/download 2>/dev/null || curl -sL https://wg.nyr.be/1/latest/download ; } | tar xz -C /usr/local/sbin/ --wildcards 'boringtun-*/boringtun' --strip-components 1
		# Configure wg-quick to use BoringTun
		mkdir /etc/systemd/system/wg-quick@wg0.service.d/ 2>/dev/null
		echo "[Service]
Environment=WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun
Environment=WG_SUDO=1" > /etc/systemd/system/wg-quick@wg0.service.d/boringtun.conf
		if [[ -n "$cron" ]] && [[ "$os" == "centos" || "$os" == "fedora" ]]; then
			systemctl enable --now crond.service
		fi
	fi
	# If firewalld was just installed, enable it
	if [[ "$firewall" == "firewalld" ]]; then
		systemctl enable --now firewalld.service
	fi
	# Generate wg0.conf
cat << EOF > /etc/wireguard/wg0.conf
# Do not alter the commented lines
# They are used by wireguard-install
# ENDPOINT $([[ -n "$public_ip" ]] && echo "$public_ip" || echo "$ip")
# IPV4_SUBNET $vpn_subnet.0/24

[Interface]
Address = $vpn_subnet.1/24$([[ -n "$ip6" ]] && echo ", fddd:2c4:2c4:2c4::1/64")
PrivateKey = $(wg genkey)
ListenPort = $port

EOF
	chmod 600 /etc/wireguard/wg0.conf
	# Enable net.ipv4.ip_forward for the system
	echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-wireguard-forward.conf
	# Enable without waiting for a reboot or service restart
	echo 1 > /proc/sys/net/ipv4/ip_forward
	if [[ -n "$ip6" ]]; then
		# Enable net.ipv6.conf.all.forwarding for the system
		echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.d/99-wireguard-forward.conf
		# Enable without waiting for a reboot or service restart
		echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
	fi
	if systemctl is-active --quiet firewalld.service; then
		# Using both permanent and not permanent rules to avoid a firewalld
		# reload.
		firewall-cmd --add-port="$port"/udp
		firewall-cmd --zone=trusted --add-source="$vpn_subnet".0/24
		firewall-cmd --permanent --add-port="$port"/udp
		firewall-cmd --permanent --zone=trusted --add-source="$vpn_subnet".0/24
		# Set NAT for the VPN subnet
		firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s "$vpn_subnet".0/24 ! -d "$vpn_subnet".0/24 -j SNAT --to "$ip"
		firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s "$vpn_subnet".0/24 ! -d "$vpn_subnet".0/24 -j SNAT --to "$ip"
		if [[ -n "$ip6" ]]; then
			firewall-cmd --zone=trusted --add-source=fddd:2c4:2c4:2c4::/64
			firewall-cmd --permanent --zone=trusted --add-source=fddd:2c4:2c4:2c4::/64
			firewall-cmd --direct --add-rule ipv6 nat POSTROUTING 0 -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to "$ip6"
			firewall-cmd --permanent --direct --add-rule ipv6 nat POSTROUTING 0 -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to "$ip6"
		fi
	else
		# Create a service to set up persistent iptables rules
		iptables_path=$(command -v iptables)
		ip6tables_path=$(command -v ip6tables)
		# nf_tables is not available as standard in OVZ kernels. So use iptables-legacy
		# if we are in OVZ, with a nf_tables backend and iptables-legacy is available.
		if [[ $(systemd-detect-virt) == "openvz" ]] && readlink -f "$(command -v iptables)" | grep -q "nft" && hash iptables-legacy 2>/dev/null; then
			iptables_path=$(command -v iptables-legacy)
			ip6tables_path=$(command -v ip6tables-legacy)
		fi
		echo "[Unit]
After=network-online.target
Wants=network-online.target
[Service]
Type=oneshot
ExecStart=$iptables_path -w 5 -t nat -A POSTROUTING -s $vpn_subnet.0/24 ! -d $vpn_subnet.0/24 -j SNAT --to $ip
ExecStart=$iptables_path -w 5 -I INPUT -p udp --dport $port -j ACCEPT
ExecStart=$iptables_path -w 5 -I FORWARD -s $vpn_subnet.0/24 -j ACCEPT
ExecStart=$iptables_path -w 5 -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
ExecStop=$iptables_path -w 5 -t nat -D POSTROUTING -s $vpn_subnet.0/24 ! -d $vpn_subnet.0/24 -j SNAT --to $ip
ExecStop=$iptables_path -w 5 -D INPUT -p udp --dport $port -j ACCEPT
ExecStop=$iptables_path -w 5 -D FORWARD -s $vpn_subnet.0/24 -j ACCEPT
ExecStop=$iptables_path -w 5 -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT" > /etc/systemd/system/wg-iptables.service
		if [[ -n "$ip6" ]]; then
			echo "ExecStart=$ip6tables_path -w 5 -t nat -A POSTROUTING -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to $ip6
ExecStart=$ip6tables_path -w 5 -I FORWARD -s fddd:2c4:2c4:2c4::/64 -j ACCEPT
ExecStart=$ip6tables_path -w 5 -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
ExecStop=$ip6tables_path -w 5 -t nat -D POSTROUTING -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to $ip6
ExecStop=$ip6tables_path -w 5 -D FORWARD -s fddd:2c4:2c4:2c4::/64 -j ACCEPT
ExecStop=$ip6tables_path -w 5 -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT" >> /etc/systemd/system/wg-iptables.service
		fi
		echo "RemainAfterExit=yes
[Install]
WantedBy=multi-user.target" >> /etc/systemd/system/wg-iptables.service
		systemctl enable --now wg-iptables.service
	fi
	# Generates the custom client.conf
	new_client_setup
	# Enable and start the wg-quick service
	systemctl enable --now wg-quick@wg0.service
	# Set up automatic updates for BoringTun if the user wanted to
	if [[ "$boringtun_updates" =~ ^[yY]$ ]]; then
		# Deploy upgrade script
		cat << 'EOF' > /usr/local/sbin/boringtun-upgrade
#!/bin/bash
latest=$(wget -qO- https://wg.nyr.be/1/latest 2>/dev/null || curl -sL https://wg.nyr.be/1/latest 2>/dev/null)
# If server did not provide an appropriate response, exit
if ! head -1 <<< "$latest" | grep -qiE "^boringtun.+[0-9]+\.[0-9]+.*$"; then
	echo "Update server unavailable"
	exit
fi
current=$(/usr/local/sbin/boringtun -V)
if [[ "$current" != "$latest" ]]; then
	download="https://wg.nyr.be/1/latest/download"
	xdir=$(mktemp -d)
	# If download and extraction are successful, upgrade the boringtun binary
	if { wget -qO- "$download" 2>/dev/null || curl -sL "$download" ; } | tar xz -C "$xdir" --wildcards "boringtun-*/boringtun" --strip-components 1; then
		systemctl stop wg-quick@wg0.service
		rm -f /usr/local/sbin/boringtun
		mv "$xdir"/boringtun /usr/local/sbin/boringtun
		systemctl start wg-quick@wg0.service
		echo "Successfully updated to $(/usr/local/sbin/boringtun -V)"
	else
		echo "boringtun update failed"
	fi
	rm -rf "$xdir"
else
	echo "$current is up to date"
fi
EOF
		chmod +x /usr/local/sbin/boringtun-upgrade
		# Add cron job to run the updater daily at a random time between 3:00 and 5:59
		{ crontab -l 2>/dev/null; echo "$(( $RANDOM % 60 )) $(( $RANDOM % 3 + 3 )) * * * /usr/local/sbin/boringtun-upgrade &>/dev/null" ; } | crontab -
	fi
	echo
	new_client_extra_setup
	print_client_qr_codes
	echo "Finished!"
	echo
	echo "The client configuration is available in:" "$script_dir"/"$client.conf"
	if [[ -e "$script_dir"/"$client-2nd-hop-upstream.conf" ]]; then
		echo "The 2nd hop upstream tun client configuration is available in:" "$script_dir"/"$client-2nd-hop-upstream.conf"
	fi
	echo "New clients can be added by running this script again."
else
	clear
	echo "WireGuard is already installed."
	echo
	echo "Select an option:"
	echo "   1) Add a new client"
	echo "   2) Remove an existing client"
	echo "   3) Add 2nd hop upstream tun"
	echo "   4) Remove 2nd hop upstream tun"
	echo "   5) Remove WireGuard"
	echo "   6) Exit"
	read -p "Option: " option
	until [[ "$option" =~ ^[1-6]$ ]]; do
		echo "$option: invalid selection."
		read -p "Option: " option
	done
	case "$option" in
		1)
			echo
			echo "Provide a name for the client:"
			read -p "Name: " unsanitized_client
			# Allow a limited lenght and set of characters to avoid conflicts
			client=$(sed 's/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-]/_/g' <<< "$unsanitized_client" | cut -c-15)
			while [[ -z "$client" ]] || grep -q "^# BEGIN_PEER $client$" /etc/wireguard/wg0.conf; do
				echo "$client: invalid name."
				read -p "Name: " unsanitized_client
				client=$(sed 's/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-]/_/g' <<< "$unsanitized_client" | cut -c-15)
			done
			echo
			new_client_dns
			new_client_setup
			# Append new client configuration to the WireGuard interface
			wg addconf wg0 <(sed -n "/^# BEGIN_PEER $client/,/^# END_PEER $client/p" /etc/wireguard/wg0.conf)
			sync_extra_in_peers
			new_client_extra_setup
			print_client_qr_codes
			echo "$client added. Configuration available in:" "$script_dir"/"$client.conf"
			if [[ -e "$script_dir"/"$client-2nd-hop-upstream.conf" ]]; then
				echo "$client 2nd hop upstream tun configuration available in:" "$script_dir"/"$client-2nd-hop-upstream.conf"
			fi
			exit
		;;
		2)
			# This option could be documented a bit better and maybe even be simplified
			# ...but what can I say, I want some sleep too
			number_of_clients=$(grep -c '^# BEGIN_PEER' /etc/wireguard/wg0.conf)
			if [[ "$number_of_clients" = 0 ]]; then
				echo
				echo "There are no existing clients!"
				exit
			fi
			echo
			echo "Select the client to remove:"
			grep '^# BEGIN_PEER' /etc/wireguard/wg0.conf | cut -d ' ' -f 3 | nl -s ') '
			read -p "Client: " client_number
			until [[ "$client_number" =~ ^[0-9]+$ && "$client_number" -le "$number_of_clients" ]]; do
				echo "$client_number: invalid selection."
				read -p "Client: " client_number
			done
			client=$(grep '^# BEGIN_PEER' /etc/wireguard/wg0.conf | cut -d ' ' -f 3 | sed -n "$client_number"p)
			echo
			read -p "Confirm $client removal? [y/N]: " remove
			until [[ "$remove" =~ ^[yYnN]*$ ]]; do
				echo "$remove: invalid selection."
				read -p "Confirm $client removal? [y/N]: " remove
			done
			if [[ "$remove" =~ ^[yY]$ ]]; then
				# The following is the right way to avoid disrupting other active connections:
				# Remove from the live interface
				wg set wg0 peer "$(sed -n "/^# BEGIN_PEER $client$/,\$p" /etc/wireguard/wg0.conf | grep -m 1 PublicKey | cut -d " " -f 3)" remove
				# Remove from the configuration file
				sed -i "/^# BEGIN_PEER $client$/,/^# END_PEER $client$/d" /etc/wireguard/wg0.conf
				sync_extra_in_peers
				echo
				echo "$client removed!"
			else
				echo
				echo "$client removal aborted!"
			fi
			exit
		;;
		3)
			add_extra_tun
			exit
		;;
		4)
			remove_extra_tun
			exit
		;;
		5)
			echo
			read -p "Confirm WireGuard removal? [y/N]: " remove
			until [[ "$remove" =~ ^[yYnN]*$ ]]; do
				echo "$remove: invalid selection."
				read -p "Confirm WireGuard removal? [y/N]: " remove
			done
			if [[ "$remove" =~ ^[yY]$ ]]; then
				if [[ -e /etc/wireguard/wg-extra-tun.env ]]; then
					remove_extra_tun
				fi
				port=$(grep '^ListenPort' /etc/wireguard/wg0.conf | cut -d " " -f 3)
				vpn_cidr=$(wg_ipv4_cidr)
				if systemctl is-active --quiet firewalld.service; then
					ip=$(firewall-cmd --direct --get-rules ipv4 nat POSTROUTING | grep -F -- "-s $vpn_cidr ! -d $vpn_cidr" | grep -oE '[^ ]+$')
					# Using both permanent and not permanent rules to avoid a firewalld reload.
					firewall-cmd --remove-port="$port"/udp
					firewall-cmd --zone=trusted --remove-source="$vpn_cidr"
					firewall-cmd --permanent --remove-port="$port"/udp
					firewall-cmd --permanent --zone=trusted --remove-source="$vpn_cidr"
					firewall-cmd --direct --remove-rule ipv4 nat POSTROUTING 0 -s "$vpn_cidr" ! -d "$vpn_cidr" -j SNAT --to "$ip"
					firewall-cmd --permanent --direct --remove-rule ipv4 nat POSTROUTING 0 -s "$vpn_cidr" ! -d "$vpn_cidr" -j SNAT --to "$ip"
					if grep -qs 'fddd:2c4:2c4:2c4::1/64' /etc/wireguard/wg0.conf; then
						ip6=$(firewall-cmd --direct --get-rules ipv6 nat POSTROUTING | grep '\-s fddd:2c4:2c4:2c4::/64 '"'"'!'"'"' -d fddd:2c4:2c4:2c4::/64' | grep -oE '[^ ]+$')
						firewall-cmd --zone=trusted --remove-source=fddd:2c4:2c4:2c4::/64
						firewall-cmd --permanent --zone=trusted --remove-source=fddd:2c4:2c4:2c4::/64
						firewall-cmd --direct --remove-rule ipv6 nat POSTROUTING 0 -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to "$ip6"
						firewall-cmd --permanent --direct --remove-rule ipv6 nat POSTROUTING 0 -s fddd:2c4:2c4:2c4::/64 ! -d fddd:2c4:2c4:2c4::/64 -j SNAT --to "$ip6"
					fi
				else
					systemctl disable --now wg-iptables.service
					rm -f /etc/systemd/system/wg-iptables.service
				fi
				systemctl disable --now wg-quick@wg0.service
				rm -f /etc/systemd/system/wg-quick@wg0.service.d/boringtun.conf
				rm -f /etc/sysctl.d/99-wireguard-forward.conf
				# Different stuff was installed depending on whether BoringTun was used or not
				if [[ "$use_boringtun" -eq 0 ]]; then
					if [[ "$os" == "ubuntu" ]]; then
						# Ubuntu
						rm -rf /etc/wireguard/
						apt-get remove --purge -y wireguard wireguard-tools
					elif [[ "$os" == "debian" ]]; then
						# Debian
						rm -rf /etc/wireguard/
						apt-get remove --purge -y wireguard wireguard-tools
					elif [[ "$os" == "centos" ]]; then
						# CentOS
						dnf remove -y wireguard-tools
						rm -rf /etc/wireguard/
					elif [[ "$os" == "fedora" ]]; then
						# Fedora
						dnf remove -y wireguard-tools
						rm -rf /etc/wireguard/
					fi
				else
					{ crontab -l 2>/dev/null | grep -v '/usr/local/sbin/boringtun-upgrade' ; } | crontab -
					if [[ "$os" == "ubuntu" ]]; then
						# Ubuntu
						rm -rf /etc/wireguard/
						apt-get remove --purge -y wireguard-tools
					elif [[ "$os" == "debian" ]]; then
						# Debian
						rm -rf /etc/wireguard/
						apt-get remove --purge -y wireguard-tools
					elif [[ "$os" == "centos" ]]; then
						# CentOS
						dnf remove -y wireguard-tools
						rm -rf /etc/wireguard/
					elif [[ "$os" == "fedora" ]]; then
						# Fedora
						dnf remove -y wireguard-tools
						rm -rf /etc/wireguard/
					fi
					rm -f /usr/local/sbin/boringtun /usr/local/sbin/boringtun-upgrade
				fi
				echo
				echo "WireGuard removed!"
			else
				echo
				echo "WireGuard removal aborted!"
			fi
			exit
		;;
		6)
			exit
		;;
	esac
fi
